name: Discord
on: [push]
jobs:
  Post-To-Discord:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send Commit Message
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          username: CustomUsername
          color: "#ff00aa"
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          description: This is a custom description.
          details: "Custom details: Somebody set up us the bomb."
          footer: This is a footer.
          text: This is where text goes.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
