name: Discord
on: [ push ]
jobs:
  Post-To-Discord:
    - name: Discord Notification
      uses: rjstone/discord-webhook-notify@v1
      with:
          severity: info
          username: TimeBot
          color: '#7FA6D0'
          avatarUrl: https://cdn.discordapp.com/avatars/529569000028373002/b5100de6821ee1c4714ac022c3cd39d9.png
          description: '${{ github.event.head_commit.message }}'
          details: [View online](${{ github.event.head_commit.url }})
          footer: ''
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}